feat: make feature importance transparent
loft-br/xgboost-survival-embeddings pull request #20
Opened 2021-02-16 18:41 UTC by GabrielGimenez

closes #14

2021-02-16 21:36 UTC, gdmarmerola-loft requested changes
this may sound a little picky, but can we use `feature_importances_` instead of `feature_importance_`?

`feature_importances_` is the pattern on sklearn, and using it may improve user experience.

2021-02-16 21:40 UTC, GabrielGimenez commented
I was intending to use the sklearn pattern, that was a typo! Thanks for reviewing

2021-02-16 21:58 UTC, davivieirab approved these changes

2021-02-17 22:30 UTC, merged

2021-03-22 14:42 UTC, ChristianMichelsen commented
Hopefully related enough to not open a new issue, but how well does this package work together with SHAP?