fix: include last tree in iteration range
loft-br/xgboost-survival-embeddings pull request #43
Opened 2021-11-10 19:56 UTC by GabrielGimenez

following xgboost docs, fix iteration range 
https://xgboost.readthedocs.io/en/latest/python/python_intro.html#prediction

2021-11-10 20:02 UTC, arthurvieira-loft requested changes

2021-11-10 20:02 UTC, arthurvieira-loft commented on xgbse/_base.py
> +                iteration_range=(0, self.bst.best_iteration + 1),
I guess it should be `self.bst.num_trees()`, and then you wouldnt need to add `+ 1`.
The `best_iteration` can be the first one, 0, even with an ensemble of 50 trees, for example.

2021-11-10 20:07 UTC, arthurvieira-loft approved these changes

2021-11-22 22:47 UTC, davivieirab approved these changes

2021-11-23 14:58 UTC, merged